# -- Overrides
# The values defined here override those in the individual charts. Some of them require tweaking
# before deployment as they are environment dependent; others are surfaced for convenience.
#
# See individual chart documentation for additional detail.

# 67 - smee dhcp, hostNetwork; NodePort? (my guess is this requires hostNetwork, NodePort (kube-proxy) won't suffice
# 69 - smee tftp, hostNetwork; NodePort? NodePort might or not suffice, no idea.
# 514 - smee syslog, hostNetwork; NodePort
# 7171 - smee http, should be directly exposed via hostNetwork (used for dhcp) anyway, but could be via NodePort or ingress too
# 50061 - hegel http. either NodePort or ingress
# 42113 - tink grpc. Either NodePort or ingress (special grpc_pass)

# Scenarios to test:
# simple bare k3s on bare vm (hostNetwork for everything, but maybe a few NodePorts needed for grpc and hegel)
# k3s clustered 2+ nodes: NodePorts for everything, can run a replica of everything on each node, only one dhcp will ever be used

hookImageServer:
  enabled: true

nodePort:
  hookImageServer:
    enabled: true
    port: 32083
  hegel:
    enabled: true
    port: 32061
  tinkGRPC:
    enabled: true
    port: 32013

showcase:
  enabled: true
  hardware:
    common:
      uefi: true
      ipv4:
        # @TODO: Use _your_ values here! Also in the ipv4.address of the devices!
        gateway: "192.168.99.1" # Must be set, otherwise no internet access; can be overriden per-device
        netmask: "255.255.255.0"
        dns: [ "192.168.66.1" ]

    devices:
      ####  Examples for use in Hook development environment.
      ####  There is a `bash build.sh build-run-qemu` command in Hook, that paired with
      ####  `export MAC=11:22:33:44:55:66 TINK_SERVER=x.y.z.y` can be used with the below "machines".
      ####  The MAC address is not really used by the qemu VM, but is passed via kernel cmdline.
      "run-qemu-x86":
        enabled: false
        mac: "11:22:33:44:55:66"
      "run-qemu-arm64":
        enabled: false
        mac: "11:22:33:44:55:77"
      
      
      ### Examples for virtual machines, ran outside of Hook's build system.
      ### Most virtualization software has support for PXE booting.
      ### You will need to have (bridging/etc) setup to get a proper IP address from a real Smee, etc.
      "vm03":
        enabled: false
        arch: aarch64
        mac: "52:54:00:01:03:03"
        rootDisk: "/dev/vdb"
        ipv4:
          address: "192.168.99.41"
        hookRef: "armbian-uefi-arm64-edge" # "default-hook-aarch64" # defined above
        imageRef: "ubuntu-jammy-cloud-arm64" # defined above
        extraKernelCommandLine: "console=ttyAMA0"
      
      "vm09":
        enabled: false
        arch: x86_64
        mac: "52:54:00:01:03:09"
        rootDisk: "/dev/vdb"
        ipv4:
          address: "192.168.99.42"
        hookRef: "armbian-uefi-x86-edge" # "default-hook-amd64" # defined above
        imageRef: "ubuntu-jammy-cloud-amd64" # defined above
        extraKernelCommandLine: "console=ttyS0"
      
      
      ###
      ### Examples for actual bare-metal hardware, mostly arm64 SBCs.
      ###
      
      # Khadas VIM3L and other meson64-based boards (u-boot)
      "vim3l":
        enabled: false
        arch: aarch64
        mac: "c8:63:14:71:2a:6d"
        rootDisk: "/dev/mmcblk0"
        ipv4:
          address: "192.168.99.51"
        hookRef: "armbian-meson64-edge"
        imageRef: "ubuntu-jammy-cloud-arm64"
        extraKernelCommandLine: "console=ttyAML0,115200"
      
      # RockPro64 and other rockchip64-based boards (u-boot)
      "rockpro64":
        enabled: false
        arch: aarch64
        mac: "2a:36:cb:a2:ae:b8"
        #rootDisk: "/dev/mmcblk2"  # mmcblk2 is the eMMC, mmcblk1 is the SD card
        rootDisk: "/dev/disk/by-id/mmc-AJTD4R_0x0b05e84d" # much safer to use this style
        ipv4:
          address: "192.168.99.52"
        hookRef: "armbian-rockchip64-edge" # defined above
        imageRef: "armbian-rpardini-rockpro64-edge-uboot" # defined above
        extraKernelCommandLine: "console=ttyS2,1500000"
      
      "orangepi3b":
        enabled: false
        arch: aarch64
        mac: "b6:a7:96:d5:f1:84"
        rootDisk: "/dev/disk/by-id/mmc-A3A551_0x2f8c5bd0" # /dev/mmcblk0 is the eMMC
        ipv4:
          address: "192.168.99.53"
        hookRef: "armbian-rockchip64-edge"
        imageRef: "armbian-rpardini-orangepi3b-edge-uboot" # defined above
        extraKernelCommandLine: "console=ttyS2,1500000"
      
      # Raspberry Pi 4B (bcm2711), using edk2 UEFI firmware on an SD card, and an external NVMe-USB disk
      "rpi4b":
        enabled: false
        arch: aarch64
        mac: "dc:a6:32:ec:8b:49"
        rootDisk: "/dev/disk/by-id/wwn-0x3001237923792379"
        ipv4:
          address: "192.168.99.54"
        hookRef: "armbian-bcm2711-current" # works, as long as UEFI is set with ACPI+DTB and no 3gb limit. Use edk2 from https://github.com/pftf/RPi4
        imageRef: "armbian-rpardini-rpi4b-current-not-efi" # defined above
        extraKernelCommandLine: "console=tty1 console=ttyAMA0,115200 loglevel=7" # Last console defined "wins", thus use tty1 last if no serial console
      
      "mekotronics-r58x-pro-via-usb":
        enabled: false
        arch: aarch64
        mac: "3c:18:a0:15:9a:9f" # 3C18A0159A9F
        ipv4:
          address: "192.168.99.55"
        hookRef: "armbian-rk35xx-legacy" # "armbian-rk35xx-vendor"
        imageRef: "armbian-rpardini-r58x-vendor-uboot"
        extraKernelCommandLine: "console=ttyFIQ0:1500000 " # console=tty1  # Last console defined "wins", thus use tty1 last if no serial console
        rootDisk: "/dev/nvme0NOENOENOENEyet"
  
  
  tinkerbell:
    hostDirectory: "/opt/hook-jolly-roger" # This will be needed in smee one day as well, to serve DTB files over TFTP for u-boot
    # These two should point to hookImageServer
    hookURL: "http://192.168.99.2:32083"
    imagesURL: "http://192.168.99.2:32083"
    # points to smee at :514
    syslogHost: "192.168.99.2"
    # tink's grpc nodeport
    grpcAuthority: "192.168.99.2:32013"
    # Hegel nodeport
    hegelURL: "http://192.168.99.2:32061"

smee:
  hostNetwork: true # no proxies, loadbalancers, or anything: it just runs as if directly on the k8s host.
  logLevel: "debug"
  tinkWorkerImage: quay.io/tinkerbell/tink-worker:v0.10.0
  image: quay.io/tinkerbellrpardini/smee:latest-rpardini # custom build with updated ipxedust and arm64 NAPNULL for u-boot's PXE-via-EFI
  # @TODO bug in smee chart, the values is under http: but the usage is not
  trustedProxies: [ "0.0.0.0/0" ] # Trust _all_ proxies, insecure
  publicIP: 192.168.99.2 # Must be set
  imagePullPolicy: Always # I re-push it there sometimes
  deployment:
    strategy: 
      type: Recreate # stop old pod before creating a new one

hegel:
  image: quay.io/tinkerbell/hegel:v0.12.0
  trustedProxies: [ "0.0.0.0/0" ] # Trust _all_ proxies, insecure

rufio:
  image: quay.io/tinkerbell/rufio:v0.3.3

tink:
  controller:
    image: quay.io/tinkerbell/tink-controller:latest # make sure we work with latest version
    imagePullPolicy: Always
  server:
    image: quay.io/tinkerbell/tink:latest # to make sure we work with the la
    imagePullPolicy: Always
