hookImageServer:
  enabled: true
  nodeSelector:
    "kubernetes.io/hostname": "mekotronics-r58x-4g-lan1.fritz.box" #  192.168.66.174 

nodePort:
  hookImageServer:
    enabled: true
    port: 32083
  hegel:
    enabled: true
    port: 32061
  tinkGRPC: # no ingress for this
    enabled: true
    port: 32013

smee:
  additionalArgs: [ "--dhcp-mode=proxy" ] # DHCP proxy mode!
  hostNetwork: true # no proxies, loadbalancers, or anything: it just runs as if directly on the k8s host.
  logLevel: "debug"
  trustedProxies: [ "0.0.0.0/0" ] # Trust _all_ proxies, insecure
  imagePullPolicy: Always # I re-push it there sometimes
  deployment:
    strategy:
      type: Recreate # stop old pod before creating a new one

hegel:
  trustedProxies: [ "0.0.0.0/0" ] # Trust _all_ proxies, insecure

tink:
  controller:
    imagePullPolicy: Always
  server:
    imagePullPolicy: Always


#### SHOWCASE. Needs to know coordinates to where Hegel / Smee (syslog, etc) and HookOS vmlinux and OS images are.
showcase:
  enabled: true

  jobs:
    enabled: true  # false to completely skip generating jobs
    nodeSelector:
      "kubernetes.io/hostname": "mekotronics-r58x-4g-lan1.fritz.box"
  
  tinkerbell:
    hostDirectory: "/opt/hook-r58x-4g" # This will be needed in smee one day as well, to serve DTB files over TFTP for u-boot
    # These two should point to hookImageServer
    hookURL: "http://192.168.66.174:32083"
    imagesURL: "http://192.168.66.174:32083"
    # points to smee at :514
    syslogHost: "192.168.66.174"
    # tink's grpc nodeport
    grpcAuthority: "192.168.66.174:32013"
    # Hegel nodeport
    hegelURL: "http://192.168.66.174:32061"
  
  
  hardware:
    common:
      uefi: true
      ipv4:
        # @TODO: Use _your_ values here! Also in the ipv4.address of the devices!
        gateway: "192.168.66.1" # Must be set, otherwise no internet access; can be overriden per-device
        netmask: "255.255.255.0"
        dns: [ "192.168.66.1" ]
        time_servers: [ "192.168.66.1" ]

    devices:
      "odroidm1":
        enabled: false
        arch: aarch64
        mac: "fe:9b:e6:5c:7d:15"
        rootDisk: "/dev/disk/by-id/nvme-WDC_WDS100T2B0C-00PXH0_21411V443507"
        ipv4:
          address: "192.168.66.124"
        hookRef: "armbian-rockchip64-edge"
        imageRef: "armbian-rpardini-odroidm1-edge-k8s" # defined above
        #imageRef: "armbian-rpardini-odroidm1-edge-uboot" # defined above
        extraKernelCommandLine: "console=ttyS2,1500000"
        userData: |
          #include https://cloud-init.pardini.net/rpardini/oldskool-rpardini/master/odroidm1_tinkerbell

      "vm06":
        enabled: true
        arch: "x86_64"
        mac: "52:54:00:01:03:06"
        rootDisk: "/dev/disk/by-id/virtio-root_disk_serial"
        ipv4:
          address: "192.168.66.76"
        hookRef: "default-hook-amd64"
        imageRef: "armbian-uefi-x86-edge-cloud-k8s"
        extraKernelCommandLine: "console=ttyS0"
        # userData is just standard cloud-init, thus supports #cloud-config and #include etc.
        # Attention: if ever ran, this gives rpardini root access to your machine. Use your own scripts;
        userData: |
          #include https://cloud-init.pardini.net/rpardini/oldskool-rpardini/master/base

  provision:
    images:
      "armbian-rpardini-odroidm1-edge-k8s":
        enabled: false
        arch: "aarch64"
        downloadURL: "https://github.com/armsurvivors/armbian-release/releases/download/24.07.21-armsurvivors-359/Armbian-unofficial_24.07.21-armsurvivors-359_Odroidm1_bookworm_edge_6.9.10-metadata-cloud-k8s-1.30.img.xz"
        image: "Armbian-unofficial_24.07.21-armsurvivors-359_Odroidm1_bookworm_edge_6.9.10-metadata-cloud-k8s-1.30.img"
        conversion: "xz-qcow2-to-img-nogz"
        doGrowPart: false # Armbian does it itself when booted
        doUserAndSshSetup: false # Armbian does it itself when booted
        doFixResolvConf: true
        doInjectHegelCloudInit: true
        rootfsPartitionNumber: "1" # rootfs is the one and only
      
      "armbian-rpardini-odroidm1-edge-uboot":
        enabled: false
        arch: "aarch64"
        downloadURL: "https://github.com/armsurvivors/armbian-release/releases/download/24.07.21-armsurvivors-358/Armbian-unofficial_24.07.21-armsurvivors-358_Odroidm1_bookworm_edge_6.9.10.img.xz"
        image: "Armbian-unofficial_24.07.21-armsurvivors-358_Odroidm1_bookworm_edge_6.9.10.img.gz"
        conversion: "xz-to-gz"
        doGrowPart: false # Armbian does it itself when booted
        doUserAndSshSetup: false # Armbian does it itself when booted
        doFixResolvConf: true
        rootfsPartitionNumber: "1"

      "armbian-uefi-x86-edge-cloud-k8s":
        enabled: false
        arch: "x86_64"
        downloadURL: "https://github.com/armsurvivors/armbian-release/releases/download/24.07.22-armsurvivors-364/Armbian-unofficial_24.07.22-armsurvivors-364_Uefi-x86_bookworm_edge_6.9.10-metadata-cloud-k8s-1.30.img.qcow2.xz"
        image: "Armbian-unofficial_24.07.22-armsurvivors-364_Uefi-x86_bookworm_edge_6.9.10-metadata-cloud-k8s-1.30.img.gz"
        conversion: "xz-qcow2-to-img-gz"
        doGrowPart: false # Armbian does it itself when booted
        doUserAndSshSetup: false # Armbian does it itself when booted
        doFixResolvConf: true
        rootfsPartitionNumber: "3" #  1 is BIOS GRUB partition thing, 2 is ESP, 3 rootfs
        espPartitionNumber: "2"
        doRestoreGRUBNormalcySeparateESP: true
        extraKernelCommandLine: "console=ttyS0" # serial console (used for grub normalcy)
