name: Validation
on:
  push:
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.4

      - name: Helm dep build for stack
        # run `helm dependency update tinkerbell/stack`` if this fails
        run: helm dependency build tinkerbell/stack/

      - name: Helm dep build for suite
        # run `helm dependency update tinkerbell/stack`` if this fails
        run: helm dependency build tinkerbell/suite/

      - name: Helm lint
        run: helm lint tinkerbell/{smee,hegel,stack,tink,showcase,suite}
